# About the dataset

Let us start the project by understanding our data.

The dataset is from Kaggle website. It contains 28 variables for 5043 movies, spanning across 100 years in 66 countries. There are 2399 unique director names, and thousands of actors/actresses. “imdb_score” is the response variable while the other 27 variables are possible predictors.

I have copied this code from "Statistical Approach for Predicting IMDB"

Link: https://www.kaggle.com/bharathraja/statistical-approach-for-predicting-imdb

The author has explained everything very syestematically

# Problem Statement

Based on the massive movie information, it would be interesting to understand what are the important factors that make a movie more successful than others. So, we would like to analyze what kind of movies are more successful, in other words, get higher IMDB score. We also want to show the results of this analysis in an intuitive way by visualizing outcome using Python.

In this project, we take IMDB scores as response variable and focus on operating predictions by analyzing the rest of variables in the IMDB 5000 movie data. The results can help film companies to understand the secret of generating a commercial success movie.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set_style('whitegrid')

In [2]:
#importing the dataset
dataset = pd.read_csv('../input/imdb-5000-movie-dataset/movie_metadata.csv')
dataset.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [3]:
dataset.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [5]:
dataset.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [6]:
dataset.shape

(5043, 28)

In [7]:
dataset.drop_duplicates(inplace=True)
dataset.shape

(4998, 28)

In [ ]:
numerical_cols = [col for col in dataset.columns if dataset[col].dtype != 'object']
categorical_cols = [col for col in dataset.columns if dataset[col].dtype == 'object']

In [9]:
dataset.describe().T

,count,mean,std,min,25%,50%,75%,max
num_critic_for_reviews,4949.0,1.398901e+02,1.214776e+02,1.00,50.00,110.00,195.00,8.130000e+02
duration,4983.0,1.072133e+02,2.524878e+01,7.00,93.00,103.00,118.00,5.110000e+02
director_facebook_likes,4895.0,6.886791e+02,2.821650e+03,0.00,7.00,49.00,192.00,2.300000e+04
actor_3_facebook_likes,4975.0,6.399009e+02,1.643298e+03,0.00,133.00,369.00,635.00,2.300000e+04
actor_1_facebook_likes,4991.0,6.556940e+03,1.506159e+04,0.00,611.50,984.00,11000.00,6.400000e+05
gross,4124.0,4.832565e+07,6.796483e+07,162.00,5304835.25,25445749.00,62319416.00,7.605058e+08
num_voted_users,4998.0,8.347020e+04,1.380866e+05,5.00,8560.00,34260.50,96120.75,1.689764e+06
cast_total_facebook_likes,4998.0,9.676941e+03,1.816540e+04,0.00,1405.50,3085.50,13740.50,6.567300e+05
facenumber_in_poster,4985.0,1.368907e+00,2.014623e+00,0.00,0.00,1.00,2.00,4.300000e+01
num_user_for_reviews,4977.0,2.720147e+02,3.777762e+02,1.00,64.00,156.00,324.00,5.060000e+03
budget,4511.0,3.974787e+07,2.069689e+08,218.00,6000000.00,20000000.00,45000000.00,1.221550e+10
title_year,4891.0,2.002469e+03,1.247524e+01,1916.00,1999.00,2005.00,2011.00,2.016000e+03
actor_2_facebook_likes,4985.0,1.642999e+03,4.030925e+03,0.00,280.00,595.00,917.00,1.370000e+05
imdb_score,4998.0,6.441056e+00,1.124107e+00,1.60,5.80,6.60,7.20,9.500000e+00
aspect_ratio,4671.0,2.221417e+00,1.391185e+00,1.18,1.85,2.35,2.35,1.600000e+01
movie_facebook_likes,4998.0,7.487430e+03,1.929073e+04,0.00,0.00,162.50,3000.00,3.490000e+05

Now let us start by filling in the NA values wherever we can!

In [10]:
color_mode = dataset['color'].mode().iloc[0]
dataset.color.fillna(color_mode, inplace = True)
dataset.color.isnull().sum()

0

In [11]:
dataset = dataset.dropna(axis = 0, subset = ['director_name'] )

In [12]:
dataset.num_critic_for_reviews.min(), dataset.num_critic_for_reviews.max(), dataset.num_critic_for_reviews.median()

(1.0, 813.0, 112.0)

In [13]:
num_critic_for_reviews_median = dataset['num_critic_for_reviews'].median()
dataset.num_critic_for_reviews.fillna(num_critic_for_reviews_median, inplace = True)
dataset.num_critic_for_reviews.isnull().sum()

0

In [14]:
duration_median = dataset.duration.median()
dataset.duration.fillna(duration_median, inplace=True)
dataset.duration.isnull().sum()

0

In [15]:
director_facebook_likes_mean = dataset.director_facebook_likes.mean()
dataset.director_facebook_likes.fillna(director_facebook_likes_mean, inplace = True)
dataset.director_facebook_likes.isnull().sum()

0

In [16]:
dataset.actor_3_facebook_likes.min(), dataset.actor_3_facebook_likes.max(), dataset.actor_3_facebook_likes.median(),dataset.actor_3_facebook_likes.mean()

(0.0, 23000.0, 372.0, 646.1009230769231)

In [17]:
actor_3_facebook_likes_mean = dataset.actor_3_facebook_likes.mean()
dataset.actor_3_facebook_likes.fillna(actor_3_facebook_likes_mean, inplace = True)
dataset.actor_3_facebook_likes.isnull().sum()

0

In [18]:
dataset = dataset.dropna(axis = 0, subset = ['actor_2_name'])
dataset.actor_2_name.isnull().sum()

0

In [19]:
actor_1_facebook_likes_mean = dataset.actor_1_facebook_likes.mean()
dataset.actor_1_facebook_likes.fillna(actor_1_facebook_likes_mean, inplace = True)
dataset.actor_1_facebook_likes.isnull().sum()

0

In [20]:
dataset = dataset.dropna(axis = 0, subset = ['gross'])
dataset.gross.isnull().sum()

0

In [21]:
dataset.shape
dataset.isnull().sum()

color                          0
director_name                  0
num_critic_for_reviews         0
duration                       0
director_facebook_likes        0
actor_3_facebook_likes         0
actor_2_name                   0
actor_1_facebook_likes         0
gross                          0
genres                         0
actor_1_name                   0
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                   7
facenumber_in_poster           7
plot_keywords                 39
movie_imdb_link                0
num_user_for_reviews           1
language                       3
country                        0
content_rating                60
budget                       263
title_year                     0
actor_2_facebook_likes         0
imdb_score                     0
aspect_ratio                 102
movie_facebook_likes           0
dtype: int64

In [22]:
dataset = dataset.dropna(axis = 0, subset = ['budget'])
dataset.budget.isnull().sum()

0

In [23]:
dataset = dataset.dropna(axis = 0, subset = ['actor_3_name'])
dataset.actor_3_name.isnull().sum()

0

In [24]:
facenumber_in_poster_median = dataset.facenumber_in_poster.median()
dataset.facenumber_in_poster.fillna(facenumber_in_poster_median, inplace = True)
dataset.facenumber_in_poster.isnull().sum()

0

In [25]:
language_mode = dataset.language.mode().iloc[0]
dataset.language.fillna(language_mode, inplace = True)
dataset.language.isnull().sum()

0

In [26]:
dataset = dataset.dropna(axis = 0, subset = ['plot_keywords'])
dataset.plot_keywords.isnull().sum()

0

In [27]:
dataset.content_rating.unique()

array(['PG-13', 'PG', 'G', 'R', 'Approved', 'NC-17', nan, 'X',
       'Not Rated', 'Unrated', 'M', 'GP', 'Passed'], dtype=object)

In [28]:
dataset.content_rating.fillna('Not Rated', inplace = True)

In [29]:
dataset.aspect_ratio.unique()

array([ 1.78,  2.35,  1.85,  2.  ,  2.2 ,  2.39,  2.24,  1.66,  1.5 ,
        1.77,  2.4 ,  1.37,   nan,  2.76,  1.33,  1.18,  2.55,  1.75,
       16.  ])

In [30]:
aspect_ratio_mode = dataset.aspect_ratio.mode().iloc[0]
dataset.aspect_ratio.fillna(aspect_ratio_mode, inplace = True)

In [31]:
dataset.isnull().sum()

color                        0
director_name                0
num_critic_for_reviews       0
duration                     0
director_facebook_likes      0
actor_3_facebook_likes       0
actor_2_name                 0
actor_1_facebook_likes       0
gross                        0
genres                       0
actor_1_name                 0
movie_title                  0
num_voted_users              0
cast_total_facebook_likes    0
actor_3_name                 0
facenumber_in_poster         0
plot_keywords                0
movie_imdb_link              0
num_user_for_reviews         0
language                     0
country                      0
content_rating               0
budget                       0
title_year                   0
actor_2_facebook_likes       0
imdb_score                   0
aspect_ratio                 0
movie_facebook_likes         0
dtype: int64

In [32]:
dataset.color.unique(), dataset.color.nunique()

(array(['Color', ' Black and White'], dtype=object), 2)

In [33]:
dataset['color'] = dataset.color.map({'Color' : 1 , ' Black and White' : 0})

In [34]:
dataset.director_name.unique(), dataset.director_name.nunique()

(array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
        'Kiyoshi Kurosawa', 'Shane Carruth', 'Neill Dela Llana'],
       dtype=object),
 1723)

In [35]:
director_name_value_counts = dataset.director_name.value_counts()
director_name_value_counts  = pd.DataFrame(director_name_value_counts).reset_index().rename(columns = {'index': 'director_name', 'director_name':'director_name_value_counts'})

In [36]:
dataset = pd.merge(dataset, director_name_value_counts,left_on = 'director_name', right_on = 'director_name', how = 'left')

In [37]:
dataset = dataset.drop(columns = 'director_name')

In [38]:
actor_2_name_value_counts = dataset.actor_2_name.value_counts()
actor_2_name_value_counts  = pd.DataFrame(actor_2_name_value_counts).reset_index().rename(columns = {'index': 'actor_2_name', 'actor_2_name':'actor_2_name_value_counts'})

In [39]:
dataset = pd.merge(dataset, actor_2_name_value_counts,left_on = 'actor_2_name', right_on = 'actor_2_name', how = 'left')

In [40]:
dataset = dataset.drop(columns = 'actor_2_name')

In [41]:
dataset.genres.unique(), dataset.genres.nunique()

(array(['Action|Adventure|Fantasy|Sci-Fi', 'Action|Adventure|Fantasy',
        'Action|Adventure|Thriller', 'Action|Thriller',
        'Action|Adventure|Sci-Fi', 'Action|Adventure|Romance',
        'Adventure|Animation|Comedy|Family|Fantasy|Musical|Romance',
        'Adventure|Family|Fantasy|Mystery', 'Action|Adventure',
        'Action|Adventure|Western', 'Action|Adventure|Family|Fantasy',
        'Action|Adventure|Comedy|Family|Fantasy|Sci-Fi',
        'Adventure|Fantasy', 'Action|Adventure|Drama|History',
        'Adventure|Family|Fantasy', 'Action|Adventure|Drama|Romance',
        'Drama|Romance', 'Action|Adventure|Sci-Fi|Thriller',
        'Action|Adventure|Fantasy|Romance',
        'Action|Adventure|Fantasy|Sci-Fi|Thriller',
        'Adventure|Animation|Comedy|Family|Fantasy',
        'Adventure|Animation|Comedy|Family|Sport', 'Action|Crime|Thriller',
        'Action|Adventure|Horror|Sci-Fi|Thriller',
        'Adventure|Animation|Family|Sci-Fi',
        'Action|Comedy|Crime|Thriller', 'Animation|Drama|Family|Fantasy',
        'Action|Crime|Drama|Thriller', 'Adventure|Animation|Comedy|Family',
        'Action|Adventure|Animation|Comedy|Family|Sci-Fi',
        'Adventure|Drama|Family|Mystery', 'Action|Comedy|Sci-Fi|Western',
        'Action|Adventure|Fantasy|Horror|Thriller',
        'Action|Adventure|Comedy|Sci-Fi', 'Comedy|Family|Fantasy',
        'Adventure|Animation|Comedy|Drama|Family|Fantasy',
        'Adventure|Drama|Family|Fantasy', 'Action|Adventure|Drama|Fantasy',
        'Action|Adventure|Family|Fantasy|Romance',
        'Action|Adventure|Drama|Sci-Fi',
        'Action|Adventure|Family|Mystery|Sci-Fi',
        'Action|Adventure|Animation|Comedy|Drama|Family|Sci-Fi',
        'Adventure|Animation|Comedy|Family|Sci-Fi',
        'Adventure|Animation|Family|Fantasy', 'Action|Sci-Fi',
        'Adventure|Drama|Sci-Fi', 'Drama|Fantasy|Romance',
        'Adventure|Sci-Fi', 'Action|Adventure|Drama|Thriller',
        'Action|Drama|History|Romance|War',
        'Action|Adventure|Biography|Drama|History|Romance|War',
        'Action|Drama', 'Drama|Horror|Sci-Fi',
        'Adventure|Comedy|Family|Fantasy',
        'Animation|Comedy|Family|Fantasy',
        'Action|Adventure|Animation|Comedy|Family',
        'Adventure|Animation|Comedy|Family|Fantasy|Musical',
        'Mystery|Thriller', 'Adventure|Animation|Comedy|Drama|Family',
        'Action|Adventure|Animation|Comedy|Family|Fantasy|Sci-Fi',
        'Comedy|Fantasy|Horror', 'Drama|Fantasy|Horror|Thriller',
        'Action|Drama|Thriller', 'Adventure',
        'Action|Comedy|Fantasy|Sci-Fi',
        'Action|Adventure|Comedy|Family|Fantasy|Mystery|Sci-Fi',
        'Action|Adventure|Animation|Fantasy', 'Comedy|Crime',
        'Action|Drama|History|War', 'Action|Adventure|Drama',
        'Action|Adventure|Animation|Comedy|Family|Fantasy',
        'Action|Drama|Mystery|Sci-Fi', 'Action|Adventure|Comedy|Thriller',
        'Action|Adventure|Animation|Fantasy|Romance|Sci-Fi',
        'Action|Adventure|Drama|History|War',
        'Adventure|Drama|Fantasy|Romance',
        'Animation|Comedy|Family|Musical',
        'Adventure|Drama|Thriller|Western',
        'Adventure|Animation|Comedy|Family|Western',
        'Action|Mystery|Thriller', 'Adventure|Sci-Fi|Thriller',
        'Adventure|Animation|Comedy|Family|Fantasy|Sci-Fi',
        'Action|Crime|Mystery|Thriller', 'Action|Adventure|Family|Mystery',
        'Adventure|Drama|Romance|War',
        'Adventure|Animation|Family|Thriller',
        'Action|Animation|Comedy|Family|Sci-Fi', 'Action|Comedy|Fantasy',
        'Adventure|Animation|Comedy|Family|Musical',
        'Action|Adventure|Crime|Mystery|Thriller',
        'Action|Adventure|History', 'Action', 'Adventure|Drama|Fantasy',
        'Action|Fantasy|Thriller', 'Action|Adventure|Comedy|Crime',
        'Adventure|Mystery|Sci-Fi', 'Action|Drama|Sci-Fi|Thriller',
        'Action|Crime|Sci-Fi|Thriller', 'Action|Family|Sport',
        'Comedy|Drama|Romance', 'Action|Comedy|Romance',
        'Action|Adventure|Mystery|Sci-Fi', 'Action|Drama|War',
        'Adventure|Drama|Sci-Fi|Thriller',
        'Action|Adventure|Comedy|Family|Fantasy', 'Crime|Thriller',
        'Action|Comedy|Crime|Romance|Thriller', 'Biography|Drama',
        'Action|Comedy|Crime|Sci-Fi|Thriller', 'Action|Drama|Fantasy|War',
        'Animation|Comedy|Family|Music|Western',
        'Action|Adventure|Mystery|Sci-Fi|Thriller',
        'Action|Drama|Sci-Fi|Sport', 'Action|Crime|Romance|Thriller',
        'Action|Adventure|Comedy', 'Biography|Drama|Sport',
        'Action|Mystery|Sci-Fi|Thriller',
        'Animation|Family|Fantasy|Musical|Romance',
        'Action|Adventure|Romance|Sci-Fi|Thriller', 'Comedy|Romance',
        'Action|Drama|Romance', 'Biography|Crime|Drama|History|Romance',
        'Biography|Crime|Drama', 'Action|Comedy|Thriller',
        'Action|Comedy|Crime', 'Action|Drama|Mystery|Thriller',
        'Drama|Western', 'Animation|Drama|Family|Musical|Romance',
        'Action|Adventure|Comedy|Family|Mystery',
        'Action|Romance|Thriller', 'Action|Fantasy|Horror|Mystery',
        'Adventure|Drama|Thriller', 'Biography|Comedy|Crime|Drama',
        'Action|Sci-Fi|War', 'Drama|Sci-Fi',
        'Action|Adventure|Animation|Family|Fantasy',
        'Action|Crime|Fantasy|Romance|Thriller', 'Adventure|Comedy|Sci-Fi',
        'Action|Crime|Sport|Thriller',
        'Action|Adventure|Biography|Drama|History|Thriller',
        'Action|Comedy|Sci-Fi', 'Action|Drama|Thriller|War',
        'Drama|Mystery|Thriller', 'Action|Adventure|Fantasy|Thriller',
        'Crime|Drama', 'Drama|History|Romance|War',
        'Animation|Comedy|Family|Sport', 'Comedy|Sci-Fi|Thriller',
        'Drama|History|War', 'Comedy',
        'Adventure|Animation|Comedy|Family|Romance',
        'Drama|Family|Fantasy|Romance', 'Drama|Fantasy|Thriller',
        'Drama|Mystery|Romance|Sci-Fi|Thriller',
        'Drama|History|War|Western', 'Action|Adventure|Animation|Family',
        'Adventure|Comedy|Family|Mystery|Sci-Fi',
        'Drama|Fantasy|Horror|Mystery|Thriller',
        'Animation|Comedy|Family|Sci-Fi',
        'Adventure|Comedy|Drama|Fantasy|Romance',
        'Action|Adventure|Comedy|Crime|Thriller', 'Crime|Drama|Thriller',
        'Adventure|Animation|Family|Fantasy|Musical|War', 'Action|Comedy',
        'Crime|Drama|Mystery|Thriller',
        'Action|Adventure|Animation|Family|Fantasy|Sci-Fi',
        'Adventure|Animation|Comedy|Family|Fantasy|Music',
        'Drama|History|Thriller|War', 'Action|Animation|Comedy|Sci-Fi',
        'Comedy|Family|Fantasy|Horror|Mystery',
        'Drama|Mystery|Sci-Fi|Thriller', 'Action|Horror|Sci-Fi|Thriller',
        'Crime|Mystery|Thriller',
        'Action|Adventure|Comedy|Crime|Mystery|Thriller',
        'Comedy|Drama|Sci-Fi', 'Action|Family|Fantasy|Musical',
        'Drama|History|Sport', 'Adventure|Drama|Romance',
        'Animation|Comedy|Family|Music|Romance',
        'Animation|Comedy|Family|Fantasy|Musical|Romance',
        'Adventure|Comedy|Family', 'Action|Crime|Drama|Mystery|Thriller',
        'Action|Adventure|Comedy|Fantasy',
        'Adventure|Comedy|Drama|Family|Fantasy',
        'Action|Comedy|Fantasy|Romance', 'Comedy|Romance|Sci-Fi',
        'Adventure|Comedy|Mystery', 'Comedy|Drama|Fantasy|Romance',
        'Action|Comedy|Family|Fantasy',
        'Action|Adventure|Fantasy|Horror|Sci-Fi',
        'Crime|Drama|History|Mystery|Thriller', 'Comedy|Drama',
        'Adventure|Animation|Comedy|Drama|Family|Fantasy|Sci-Fi',
        'Action|Drama|Romance|Sci-Fi|Thriller', 'Comedy|Crime|Sport',
        'Comedy|Family|Fantasy|Romance',
        'Adventure|Drama|History|Romance|War', 'Comedy|Family|Sci-Fi',
        'Fantasy|Horror|Mystery|Thriller',
        'Adventure|Animation|Comedy|Family|Fantasy|Sci-Fi|Sport',
        'Adventure|Comedy|Crime|Family|Mystery', 'Drama|Sci-Fi|Thriller',
        'Action|Crime|Mystery|Romance|Thriller',
        'Action|Adventure|Comedy|Romance',
        'Adventure|Animation|Family|Western', 'Comedy|Family|Romance',
        'Action|Adventure|Family|Sci-Fi|Thriller',
        'Animation|Family|Fantasy|Music',
        'Action|Adventure|Family|Fantasy|Thriller', 'Comedy|Fantasy',
        'Action|Adventure|Comedy|Fantasy|Thriller',
        'Action|Sci-Fi|Thriller', 'Drama|History|Thriller',
        'Adventure|Animation|Family', 'Drama|Musical|Romance',
        'Documentary|Drama', 'Action|Adventure|Drama|History|Romance',
        'Adventure|Animation|Drama|Family|Musical',
        'Animation|Comedy|Family|Fantasy|Sci-Fi',
        'Adventure|Animation|Drama|Family|Fantasy', 'Sci-Fi|Thriller',
        'Animation|Comedy|Family', 'Action|Crime|Fantasy|Thriller',
        'Comedy|Drama|Family|Music|Musical|Romance',
        'Horror|Mystery|Thriller', 'Action|Adventure|Comedy|Family|Sci-Fi',
        'Comedy|Family', 'Biography|Comedy|Drama|History',
        'Drama|Music|Musical', 'Comedy|Crime|Music',
        'Action|Comedy|Romance|Thriller',
        'Animation|Comedy|Family|Fantasy|Mystery',
        'Comedy|Crime|Drama|Romance', 'Action|Adventure|Romance|Thriller',
        'Drama|History|Romance', 'Action|Drama|Fantasy|Romance',
        'Action|Adventure|Animation|Family|Sci-Fi', 'Action|Drama|Sci-Fi',
        'Animation|Comedy|Fantasy', 'Action|Fantasy',
        'Action|Animation|Comedy|Family',
        'Action|Adventure|Comedy|Romance|Thriller', 'Action|Comedy|Sport',
        'Biography|Drama|History|War', 'Adventure|Animation|Comedy',
        'Action|Drama|Sport', 'Adventure|Drama|Family',
        'Drama|Mystery|Romance|Thriller',
        'Adventure|Animation|Comedy|Family|Fantasy|Romance',
        'Adventure|Drama|War', 'Action|Adventure|Crime|Thriller',
        'Fantasy|Mystery|Romance|Sci-Fi|Thriller',
        'Drama|Fantasy|Mystery|Thriller',
        'Animation|Comedy|Family|Fantasy|Music',
        'Drama|Horror|Romance|Thriller', 'Drama|War', 'Drama',
        'Action|Drama|Fantasy|Horror|War',
        'Adventure|Family|Fantasy|Romance',
        'Adventure|Biography|Drama|History|War',
        'Action|Adventure|Horror|Sci-Fi', 'Action|Fantasy|Horror',
        'Comedy|Drama|Musical|Romance', 'Action|Sci-Fi|Sport',
        'Action|Adventure|Animation|Comedy|Crime|Family|Fantasy',
        'Adventure|Animation|Family|Fantasy|Musical',
        'Action|Crime|Mystery|Sci-Fi|Thriller',
        'Action|Comedy|Crime|Drama|Thriller',
        'Adventure|Drama|History|Romance', 'Biography|Drama|Thriller',
        'Action|Adventure|Fantasy|War', 'Comedy|Fantasy|Romance',
        'Drama|Horror|Sci-Fi|Thriller', 'Adventure|Drama|History',
        'Action|Adventure|Comedy|Romance|Thriller|Western',
        'Biography|Drama|Sport|War', 'Comedy|Drama|Family|Musical',
        'Action|Adventure|Fantasy|Horror|Sci-Fi|Thriller', 'Drama|Sport',
        'Action|Fantasy|Sci-Fi|Thriller', 'Drama|Mystery|Romance',
        'Adventure|Biography|Drama|History|Sport|Thriller',
        'Crime|Drama|Fantasy', 'Adventure|Biography|Crime|Drama|Western',
        'Action|War', 'Comedy|Romance|Sport',
        'Crime|Drama|Mystery|Thriller|Western', 'Comedy|Sport',
        'Comedy|Drama|Family', 'Crime|Drama|Fantasy|Mystery',
        'Adventure|Animation|Biography|Drama|Family|Fantasy|Musical',
        'Drama|Romance|Western', 'Documentary|Music', 'Drama|Thriller',
        'Animation|Family|Fantasy', 'Action|Fantasy|Horror|Sci-Fi',
        'Biography|Comedy|Drama', 'Action|Horror|Sci-Fi',
        'Adventure|Comedy', 'Biography|Drama|History|Sport',
        'Comedy|Crime|Romance|Thriller', 'Comedy|Crime|Romance',
        'Horror|Mystery|Sci-Fi|Thriller', 'Biography|Drama|Music',
        'Drama|Fantasy|Sport', 'Adventure|Comedy|Drama|Music',
        'Action|Fantasy|Horror|Sci-Fi|Thriller',
        'Adventure|Animation|Comedy|Drama|Family|Fantasy|Romance',
        'Horror|Sci-Fi|Thriller', 'Drama|Fantasy|Mystery|Romance|Thriller',
        'Action|Adventure|Drama|History|Romance|War',
        'Drama|Fantasy|Mystery|Romance', 'Fantasy|Horror|Mystery|Romance',
        'Adventure|Comedy|Family|Romance|Sci-Fi', 'Drama|Horror|Thriller',
        'Action|Comedy|Mystery|Romance',
        'Action|Adventure|Comedy|Romance|Sci-Fi',
        'Action|Biography|Drama|History|Thriller|War',
        'Adventure|Comedy|Family|Fantasy|Horror',
        'Comedy|Family|Romance|Sci-Fi', 'Action|Adventure|Thriller|War',
        'Comedy|Drama|Romance|Sport', 'Action|Comedy|Crime|Drama',
        'Drama|Music|Romance|War', 'Action|Comedy|Drama|Family|Thriller',
        'Action|Crime',
        'Adventure|Animation|Drama|Family|History|Musical|Romance',
        'Action|Adventure|Drama|Romance|Sci-Fi',
        'Action|Adventure|Comedy|Family|Romance',
        'Action|Adventure|Comedy|Western',
        'Biography|Drama|History|Musical',
        'Adventure|Drama|Horror|Thriller', 'Action|Drama|Sport|Thriller',
        'Drama|Musical|Romance|Thriller', 'Comedy|Drama|Family|Fantasy',
        'Adventure|Comedy|Crime|Family|Musical',
        'Drama|Music|Musical|Romance', 'Drama|Mystery|Romance|War',
        'Action|Adventure|Romance|Sci-Fi',
        'Adventure|Animation|Drama|Family|Fantasy|Musical|Mystery|Romance',
        'Action|Horror|Thriller', 'Drama|History|Horror',
        'Drama|Romance|Sport', 'Comedy|Family|Musical|Romance',
        'Romance|Sci-Fi|Thriller', 'Biography|Comedy|Drama|Romance',
        'Mystery|Sci-Fi|Thriller', 'Drama|Fantasy|Horror',
        'Adventure|Comedy|Drama|Fantasy|Musical',
        'Action|Adventure|Family|Fantasy|Sci-Fi|Thriller',
        'Adventure|Comedy|Family|Fantasy|Romance|Sport',
        'Adventure|Horror|Mystery', 'Crime|Drama|Romance|Thriller',
        'Comedy|Crime|Drama|Thriller', 'Drama|Fantasy',
        'Adventure|Comedy|Drama', 'Action|Biography|Drama|History|War',
        'Adventure|Comedy|Fantasy', 'Adventure|Comedy|Crime|Drama|Family',
        'Action|Biography|Crime|Drama|Thriller', 'Comedy|Sci-Fi',
        'Action|Adventure|Comedy|Crime|Music|Mystery',
        'Action|Crime|Drama|Sci-Fi|Thriller',
        'Action|Adventure|Comedy|Drama|War', 'Drama|Mystery|Sci-Fi',
        'Crime|Drama|Music', 'Adventure|Crime|Drama|Western',
        'Comedy|Drama|Thriller',
        'Action|Comedy|Crime|Music|Romance|Thriller',
        'Crime|Romance|Thriller', 'Action|Adventure|Drama|Sci-Fi|Thriller',
        'Action|Drama|Fantasy|Thriller|Western',
        'Action|Drama|Mystery|Thriller|War', 'Action|Comedy|Crime|Romance',
        'Action|Adventure|Family|Fantasy|Sci-Fi',
        'Adventure|Comedy|Family|Musical', 'Action|Horror',
        'Action|Adventure|Horror|Thriller', 'Comedy|Drama|Music|Romance',
        'Action|Crime|Drama|Romance|Thriller',
        'Comedy|Family|Romance|Sport', 'Drama|Family|Fantasy',
        'Drama|Fantasy|Musical|Romance',
        'Adventure|Comedy|Family|Fantasy|Sci-Fi', 'Comedy|Musical',
        'Biography|Drama|History', 'Action|Crime|Drama|Thriller|War',
        'Comedy|Crime|Thriller', 'Biography|Drama|History|Thriller',
        'Action|Adventure|Crime|Drama|Mystery|Thriller',
        'Animation|Family|Fantasy|Musical', 'Adventure|Drama|Western',
        'Biography|Drama|History|Romance', 'Drama|Horror|Mystery|Thriller',
        'Action|Fantasy|Western', 'Drama|Music',
        'Action|Drama|Family|Sport', 'Action|Biography|Drama|Thriller|War',
        'Comedy|Drama|Sport', 'Horror|Mystery',
        'Adventure|Comedy|Sci-Fi|Western', 'Fantasy|Horror|Romance',
        'Biography|Drama|Romance', 'Action|Adventure|Drama|Romance|War',
        'Adventure|Comedy|Crime|Romance',
        'Comedy|Drama|Family|Fantasy|Romance', 'Horror',
        'Action|Adventure|Drama|Romance|Thriller',
        'Biography|Drama|Music|Musical', 'Drama|History', 'Comedy|Western',
        'Action|Adventure|Crime|Fantasy|Mystery|Thriller',
        'Adventure|Drama|Mystery', 'Biography|Crime|Drama|Music',
        'Crime|Drama|Horror|Thriller', 'Horror|Thriller',
        'Adventure|Animation|Comedy|Drama|Family|Fantasy|Musical',
        'Action|Adventure|Comedy|Music|Thriller',
        'Adventure|Animation|Comedy|Crime|Family',
        'Comedy|Romance|Sci-Fi|Thriller', 'Comedy|Crime|Family|Romance',
        'Crime|Horror|Thriller', 'Action|Horror|Mystery|Sci-Fi|Thriller',
        'Comedy|Fantasy|Sci-Fi',
        'Adventure|Animation|Comedy|Fantasy|Romance',
        'Action|Adventure|Family|Thriller',
        'Adventure|Comedy|Drama|Romance|Thriller|War',
        'Action|Drama|Fantasy', 'Action|Adventure|Drama|Fantasy|War',
        'Drama|Fantasy|Romance|Sci-Fi',
        'Animation|Comedy|Family|Horror|Sci-Fi',
        'Biography|Drama|Romance|Sport', 'Action|Biography|Drama',
        'Adventure|Drama', 'Horror|Mystery|Sci-Fi',
        'Action|Adventure|Drama|Thriller|Western',
        'Adventure|Family|Fantasy|Sci-Fi', 'Action|Biography|Drama|Sport',
        'Drama|Family',
        'Action|Adventure|Crime|Drama|Family|Fantasy|Romance|Thriller',
        'Biography|Comedy|Romance', 'Action|Biography|Drama|History',
        'Biography|Drama|War', 'Drama|Romance|War',
        'Adventure|Comedy|Family|Sci-Fi',
        'Biography|Drama|Family|History|Sport',
        'Biography|Comedy|Drama|History|Music', 'Fantasy|Horror',
        'Comedy|Drama|Romance|Sci-Fi',
        'Adventure|Animation|Comedy|Family|War',
        'Action|Comedy|Sci-Fi|Thriller', 'Comedy|Horror',
        'Drama|Thriller|War', 'Comedy|Music', 'Action|Western',
        'Action|Adventure|Family|Sci-Fi',
        'Adventure|Biography|Drama|Thriller', 'Drama|Romance|War|Western',
        'Action|Adventure|Comedy|Drama|Thriller', 'Drama|Music|Romance',
        'Action|Adventure|Crime|Drama|Thriller',
        'Crime|Horror|Mystery|Thriller', 'Adventure|Comedy|Family|Sport',
        'Comedy|Drama|Fantasy', 'Comedy|Family|Sport',
        'Action|Adventure|Drama|Family', 'Drama|Family|Sport',
        'Action|Thriller|Western', 'Action|Drama|Fantasy|Horror|Thriller',
        'Animation|Comedy|Family|Fantasy|Musical',
        'Action|Crime|Drama|Mystery|Sci-Fi|Thriller',
        'Adventure|Comedy|Crime|Drama', 'Drama|Mystery',
        'Comedy|Fantasy|Horror|Thriller',
        'Crime|Drama|Mystery|Sci-Fi|Thriller', 'Comedy|Crime|Musical',
        'Comedy|Drama|Family|Music|Romance', 'Comedy|Horror|Romance',
        'Comedy|Family|Fantasy|Sport',
        'Animation|Comedy|Family|Mystery|Sci-Fi',
        'Animation|Drama|Family|Fantasy|Musical|Romance',
        'Comedy|Horror|Musical|Sci-Fi', 'Crime|Drama|Sport',
        'Action|Adventure|Animation|Drama|Mystery|Sci-Fi|Thriller',
        'Action|Adventure|Crime|Drama|Romance', 'Action|Comedy|Horror',
        'Adventure|Horror|Thriller', 'Adventure|Fantasy|Mystery',
        'Biography|Crime|Drama|History|Western',
        'Action|Biography|Crime|Drama', 'Biography|Drama|Music|Romance',
        'Biography|Crime|Drama|History|Music',
        'Adventure|Animation|Comedy|Drama|Family|Musical',
        'Comedy|Drama|Music', 'Drama|Romance|Thriller',
        'Action|Fantasy|Horror|Thriller', 'Adventure|Biography',
        'Action|Comedy|Family', 'Action|Horror|Romance',
        'Action|Comedy|Crime|Music',
        'Action|Drama|Fantasy|Mystery|Sci-Fi|Thriller',
        'Action|Crime|Drama|History|Western', 'Comedy|Crime|Drama',
        'Comedy|Family|Fantasy|Music|Romance',
        'Adventure|Comedy|Crime|Music',
        'Action|Adventure|Comedy|Sci-Fi|Thriller',
        'Action|Crime|Drama|Western',
        'Action|Adventure|Comedy|Family|Romance|Sci-Fi',
        'Action|Fantasy|Romance|Sci-Fi', 'Comedy|Crime|Mystery|Romance',
        'Adventure|Family', 'Comedy|Drama|Family|Romance',
        'Action|Drama|Music|Romance',
        'Adventure|Comedy|Family|Fantasy|Horror|Mystery',
        'Action|Biography|Drama|History|Romance|Western',
        'Biography|Drama|Family',
        'Action|Adventure|Comedy|Crime|Family|Romance|Thriller',
        'Drama|Romance|Sci-Fi', 'Comedy|Fantasy|Horror|Romance',
        'Comedy|Family|Music', 'Action|Comedy|Music',

In [42]:
dataset['main_genre'] = dataset.genres.str.split('|').str[0]

In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['main_genre'] = le.fit_transform(dataset.main_genre)

In [44]:
genres_value_counts = dataset.genres.value_counts()

In [45]:
genres_value_counts  = pd.DataFrame(genres_value_counts).reset_index().rename(columns = {'index' : 'genres', 'genres' : 'genres_value_counts'})

In [46]:
dataset = pd.merge(dataset, genres_value_counts,left_on = 'genres', right_on = 'genres', how = 'left')

In [47]:
dataset = dataset.drop(columns = 'genres')

In [48]:
dataset.actor_1_name.unique(), dataset.actor_1_name.nunique()

(array(['CCH Pounder', 'Johnny Depp', 'Christoph Waltz', ...,
        'Carlos Gallardo', 'Kerry Bishé', 'John August'], dtype=object),
 1485)

In [49]:
actor_1_name_value_counts = dataset.actor_1_name.value_counts()

In [50]:
actor_1_name_value_counts = pd.DataFrame(actor_1_name_value_counts).reset_index().rename(columns = {'index' : 'actor_1_name', 'actor_1_name' : 'actor_1_name_value_counts'})

In [51]:
dataset = pd.merge(dataset, actor_1_name_value_counts,left_on = 'actor_1_name', right_on = 'actor_1_name', how = 'left')

In [52]:
dataset = dataset.drop(columns = 'actor_1_name')

In [53]:
dataset = dataset.drop(columns = 'movie_title')

In [54]:
actor_3_name_value_counts = dataset.actor_3_name.value_counts()

In [55]:
actor_3_name_value_counts = pd.DataFrame(actor_3_name_value_counts).reset_index().rename(columns = {'index' : 'actor_3_name', 'actor_3_name' : 'actor_3_name_value_counts'})

In [56]:
dataset= pd.merge(dataset, actor_3_name_value_counts,left_on = 'actor_3_name', right_on = 'actor_3_name', how = 'left')

In [57]:
dataset = dataset.drop(columns = 'actor_3_name')

In [58]:
dataset['main_plot_keyword'] = dataset.plot_keywords.str.split('|').str[0]

In [59]:
dataset = dataset.drop(columns = 'plot_keywords')

In [60]:
main_plot_keyword_value_counts = dataset.main_plot_keyword.value_counts()
main_plot_keyword_value_counts = pd.DataFrame(main_plot_keyword_value_counts).reset_index().rename(columns = {'index' : 'main_plot_keyword', 'main_plot_keyword' : 'main_plot_keyword_value_counts'})

In [61]:
dataset = pd.merge(dataset, main_plot_keyword_value_counts, left_on = 'main_plot_keyword', right_on = 'main_plot_keyword', how = 'left')
dataset = dataset.drop(columns = 'main_plot_keyword')

In [62]:
dataset = dataset.drop(columns = 'movie_imdb_link')

In [63]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
dataset['language'] = le1.fit_transform(dataset.language)

In [64]:
from sklearn.preprocessing import LabelEncoder
le2 = LabelEncoder()
dataset['country'] = le2.fit_transform(dataset.country)

In [65]:
from sklearn.preprocessing import LabelEncoder
le3 = LabelEncoder()
dataset['content_rating'] = le3.fit_transform(dataset.content_rating)

In [66]:
dataset.head().T

,0,1,2,3,4
color,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
num_critic_for_reviews,7.230000e+02,3.020000e+02,6.020000e+02,8.130000e+02,4.620000e+02
duration,1.780000e+02,1.690000e+02,1.480000e+02,1.640000e+02,1.320000e+02
director_facebook_likes,0.000000e+00,5.630000e+02,0.000000e+00,2.200000e+04,4.750000e+02
actor_3_facebook_likes,8.550000e+02,1.000000e+03,1.610000e+02,2.300000e+04,5.300000e+02
actor_1_facebook_likes,1.000000e+03,4.000000e+04,1.100000e+04,2.700000e+04,6.400000e+02
gross,7.605058e+08,3.094042e+08,2.000742e+08,4.481306e+08,7.305868e+07
num_voted_users,8.862040e+05,4.712200e+05,2.758680e+05,1.144337e+06,2.122040e+05
cast_total_facebook_likes,4.834000e+03,4.835000e+04,1.170000e+04,1.067590e+05,1.873000e+03
facenumber_in_poster,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00
num_user_for_reviews,3.054000e+03,1.238000e+03,9.940000e+02,2.701000e+03,7.380000e+02
language,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
country,4.500000e+01,4.500000e+01,4.400000e+01,4.500000e+01,4.500000e+01
content_rating,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00
budget,2.370000e+08,3.000000e+08,2.450000e+08,2.500000e+08,2.637000e+08
title_year,2.009000e+03,2.007000e+03,2.015000e+03,2.012000e+03,2.012000e+03
actor_2_facebook_likes,9.360000e+02,5.000000e+03,3.930000e+02,2.300000e+04,6.320000e+02
imdb_score,7.900000e+00,7.100000e+00,6.800000e+00,8.500000e+00,6.600000e+00
aspect_ratio,1.780000e+00,2.350000e+00,2.350000e+00,2.350000e+00,2.350000e+00
movie_facebook_likes,3.300000e+04,0.000000e+00,8.500000e+04,1.640000e+05,2.400000e+04
director_name_value_counts,7.000000e+00,7.000000e+00,8.000000e+00,8.000000e+00,3.000000e+00
actor_2_name_value_counts,3.000000e+00,7.000000e+00,2.000000e+00,5.000000e+00,3.000000e+00
main_genre,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
genres_value_counts,1.200000e+01,2.500000e+01,4.500000e+01,2.200000e+01,4.600000e+01
actor_1_name_value_counts,4.000000e+00,3.800000e+01,4.000000e+00,9.000000e+00,2.000000e+00
actor_3_name_value_counts,3.000000e+00,4.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00
main_plot_keyword_value_counts,2.000000e+00,1.000000e+00,7.000000e+00,2.000000e+00,6.900000e+01

In [67]:
datasetR = dataset.copy() #lets keep our original dataset for reference. Here datasetR is for Regression model
datasetC = dataset.copy() #Here datasetC is for classification model

In [68]:
from sklearn.model_selection import train_test_split
y = datasetR.pop('imdb_score')
X = datasetR
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, test_size = 0.2, random_state = 42)

In [69]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train.values), columns=X_train.columns, index=X_train.index)

In [70]:
X_test = pd.DataFrame(scaler.transform(X_test.values), columns = X_train.columns, index = X_test.index)

In [71]:
def correlation(dataset, threshold):
    col_corr = set() # Set of all the names of deleted columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if (corr_matrix.iloc[i, j] >= threshold) and (corr_matrix.columns[j] not in col_corr):
                colname = corr_matrix.columns[i] # getting the name of column
                col_corr.add(colname)
                if colname in dataset.columns:
                    del dataset[colname] # deleting the column from the dataset
correlation(X_train,0.90)

In [72]:
#importing the required libraries
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [73]:
# Running RFE with the output number of the variable equal to 15
lm = LinearRegression()
lm.fit(X_train, y_train)

rfe = RFE(lm, 15)            # running RFE
rfe = rfe.fit(X_train, y_train)

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=15 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)

In [74]:
col_rfe = X_train.columns[rfe.support_]
col_rfe

Index(['color', 'num_critic_for_reviews', 'duration', 'actor_3_facebook_likes',
       'actor_1_facebook_likes', 'gross', 'num_voted_users',
       'facenumber_in_poster', 'num_user_for_reviews', 'language', 'budget',
       'title_year', 'actor_2_facebook_likes', 'movie_facebook_likes',
       'main_genre'],
      dtype='object')

In [75]:
#Creating a X_train dataframe with rfe varianles
X_train_rfe = X_train[col_rfe]

In [76]:
# Adding a constant variable for using the stats model
import statsmodels.api as sm
X_train_rfe_constant = sm.add_constant(X_train_rfe)

In [77]:
lm = sm.OLS(y_train,X_train_rfe_constant).fit()   # Running the linear model
#Let's see the summary of our linear model
print(lm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             imdb_score   R-squared:                       0.377
Model:                            OLS   Adj. R-squared:                  0.374
Method:                 Least Squares   F-statistic:                     122.4
Date:                Tue, 20 Apr 2021   Prob (F-statistic):          7.83e-298
Time:                        14:01:51   Log-Likelihood:                -3793.9
No. Observations:                3053   AIC:                             7620.
Df Residuals:                    3037   BIC:                             7716.
Df Model:                          15
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                      6.8264      0.180     37.892      0.000       6.473       7.180
color                     -0.3608      0.086     -4.220      0.000      -0.528      -0.193
num_critic_for_reviews     2.0974      0.178     11.753      0.000       1.747       2.447
duration                   2.9343      0.220     13.312      0.000       2.502       3.367
actor_3_facebook_likes    -1.0232      0.245     -4.172      0.000      -1.504      -0.542
actor_1_facebook_likes     0.9896      0.688      1.438      0.150      -0.359       2.339
gross                     -1.0088      0.200     -5.049      0.000      -1.401      -0.617
num_voted_users            6.4188      0.323     19.902      0.000       5.786       7.051
facenumber_in_poster      -1.1126      0.313     -3.556      0.000      -1.726      -0.499
num_user_for_reviews      -3.4556      0.332    -10.414      0.000      -4.106      -2.805
language                   1.5674      0.203      7.703      0.000       1.168       1.966
budget                    -1.1040      0.611     -1.806      0.071      -2.302       0.094
title_year                -2.0488      0.177    -11.547      0.000      -2.397      -1.701
actor_2_facebook_likes     0.3081      0.152      2.026      0.043       0.010       0.606
movie_facebook_likes      -0.3907      0.228     -1.713      0.087      -0.838       0.056
main_genre                 0.4281      0.085      5.052      0.000       0.262       0.594
==============================================================================
Omnibus:                      471.393   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              994.415
Skew:                          -0.916   Prob(JB):                    1.16e-216
Kurtosis:                       5.113   Cond. No.                         78.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [78]:
X_test_rfe = X_test[col_rfe]
X_test_rfe_constant = sm.add_constant(X_test_rfe)
y_pred_linear = lm.predict(X_test_rfe_constant)
y_pred_linear.values

array([ 7.01444312,  6.00876198,  6.62347135,  6.59482027,  6.18268366,
        6.79254053,  6.71765315,  6.25384279,  6.08470355,  7.20717633,
        5.71014709,  6.06612977,  5.9959564 ,  6.64196818,  6.08914272,
        7.42534011,  6.98659027,  6.18680856,  6.7656102 ,  5.84074487,
        5.88570792,  6.27443048,  6.38443962,  6.45300389,  5.94810376,
        6.55519627,  6.83348579,  6.78324774,  7.49528209,  6.7076033 ,
        6.41911769,  6.91743602,  6.19909485,  8.5792837 ,  5.99658715,
        6.1153123 ,  6.07696256,  8.68334707,  6.58889215,  6.4787575 ,
        6.39522147,  7.5316076 ,  5.82752705,  6.28471002,  6.73123554,
        5.72430876,  6.07725613,  6.02306239,  5.93702133,  5.46658224,
        6.4272058 ,  6.07471918,  5.74102048,  6.38838576,  7.40419389,
        6.40289355,  5.98113985,  7.70453531,  8.19492268,  6.7685695 ,
        7.04712224,  6.80422735,  9.94078061,  7.01846469,  8.20775291,
        6.33402399,  6.35680065,  5.54112474,  6.49460001,  6.95320643,
        6.1077915 ,  6.77861348,  5.89979206,  6.11757466,  6.56769757,
        6.07898786,  6.09894807,  6.34864654,  6.28462213,  6.06344886,
        6.67896183,  6.26708125,  5.6900226 ,  6.09804496,  7.17687135,
        6.80343483,  9.2936546 ,  6.25060878,  5.97708893,  5.98551069,
        6.53302944,  6.86141968,  6.4195812 ,  6.83240642,  6.71601208,
        7.3574184 ,  6.26536451,  7.26739823,  6.33981875,  6.69735576,
        5.85849456,  6.65665419,  6.36601689,  6.22925778,  6.26067074,
        6.06169243,  7.19567132,  6.35786519,  7.6193287 ,  6.43435955,
        6.79051612,  6.86136887,  6.32813145,  5.74222925,  6.68259266,
        6.61671119,  5.74009576,  7.00903988,  7.74325908,  6.11405286,
        7.60989869,  6.19226116,  5.81163381,  6.52134254,  6.20032616,
        6.59550285,  7.52259346,  5.99911076,  5.98384559,  5.84605346,
        6.54537472,  5.86255861,  6.06715117,  6.38005338,  6.47530756,
        6.11636882,  5.71504247,  6.53060277,  7.23602877,  7.9957383 ,
        6.08008597,  6.57033402,  7.6836214 ,  6.20019198,  6.03092416,
        6.24876309,  6.23726326,  6.57265252,  6.17005615,  6.20210799,
        6.77262489,  6.19147131,  6.76991856,  5.92795216,  6.06377103,
        6.61585331,  7.06441291,  6.19610145,  6.46782712,  6.37241704,
        5.63586991,  7.25474476,  6.96829038,  6.78625748,  6.46503481,
        6.23551168,  5.92419713,  6.24987751,  7.67712297,  6.24988283,
        5.84008071,  7.94358893,  6.29906698,  7.1589256 ,  6.29195319,
        6.75674225,  6.40587035,  6.48889574,  7.14505097,  6.86725381,
        6.18502399,  5.51875208,  5.96539252,  6.04442617,  6.29465585,
        6.04802445,  5.99975866,  8.00829088,  7.12744368,  6.2979498 ,
        6.5537354 ,  6.80870917,  5.91064586,  6.43525308,  6.77667533,
        7.57716341,  6.21157027,  6.6172308 ,  6.42923658,  6.05737647,
        6.81780002,  6.67406536,  6.43954199,  6.09379252,  7.56872381,
        6.64216546,  6.2982413 ,  6.22231666,  5.9404799 ,  6.72407447,
        5.88988139,  6.66384966,  6.20501767,  6.10281328,  5.4427566 ,
        6.26981833,  6.13922053,  6.4088028 ,  7.26330704,  6.48447318,
        6.33907907,  6.0144283 ,  6.26902963,  5.93925155,  6.2237208 ,
        6.19056256,  6.22034983,  7.11237893,  6.30074649,  7.92732917,
        6.41444925,  6.62002941,  6.07222206,  6.01523054,  6.54264732,
        6.37123441,  6.49492952,  6.13655517,  7.36435425,  7.04562505,
        8.97696393,  6.51025593,  6.04980787,  6.40145846,  6.37170652,
        6.15351051,  5.78637192,  6.54410199,  6.05597997,  5.99549414,
        5.59407126,  5.99662106,  6.74887423,  5.54502022,  6.09649921,
        6.55840164,  6.49347791,  7.27922689,  5.77079801,  6.58741183,
        6.22805196,  6.30303214,  6.10993779,  5.94756547,  5.54521954,
        6.42095279,  6.02265969,  6.27956521,  5.92152949,  6.73473049,
        5.68540873,  6.50954598,  6.08873957,  6.21163015,  6.15199405,
        6.71236178,  5.78244426,  6.06810501,  6.30729665,  6.49903286,
        7.06540656,  5.94969899,  7.31455884,  5.87292106,  8.23923134,
        5.87083642,  5.9582297 ,  6.18313475,  6.14879359,  5.98514567,
        6.27524655,  6.32182334,  6.5007595 ,  6.17042473,  6.79076453,
        5.9049523 ,  6.65665343,  6.36022798,  6.46280353,  6.01718958,
        6.28119645,  6.50855401,  6.27367248,  5.66700574,  6.33183109,
        6.71268603,  7.283805  ,  6.22250404,  6.07339987,  6.04154328,
        6.45677419,  5.72348801,  4.22900969,  8.05556047,  5.96250053,
        6.53225024,  6.00109631,  7.3317144 ,  7.51401592,  5.8766708 ,
        6.20029658,  6.01078157,  6.80142277,  5.67930959,  7.92583261,
        6.00090556,  5.77468913,  7.46833602,  6.73391619,  9.2914372 ,
        6.20960017,  6.70260262,  6.24221717,  5.85058944,  6.73499364,
        5.81114328,  7.04249081,  6.32907046,  6.274517  ,  5.9889109 ,
        5.81824617,  6.58427659,  6.49183953,  5.73546766,  7.19559454,
        6.15443868,  6.74877786,  6.07017485,  5.79045305,  6.6413898 ,
        8.189022  ,  6.00257543,  6.21917704,  5.95772676,  6.61659413,
        7.51270485,  6.86250378,  6.17017735,  5.90496364,  6.29030756,
        6.6783423 ,  6.48925282,  6.19443718,  6.33952312,  7.26164821,
        6.04380702,  6.70863009,  5.90751674,  7.08487218,  6.71024076,
        6.05406687,  5.88335329,  6.94040368,  6.10684993,  7.1927546 ,
        6.8115464 ,  5.79862251,  5.79539035,  6.39321974,  6.00895891,
        6.44311272,  6.45231899,  6.16807742,  6.09958337,  6.44488228,
        7.09042015,  6.26943513,  6.49391649,  6.34107833,  6.39115242,
        5.90563051,  6.09634274,  8.08887053,  6.10393951,  5.78627411,
        5.92374689,  5.95016789,  5.93949908,  6.4731637 ,  8.44826466,
        5.69480182,  6.70363477,  6.51495503,  5.9131167 ,  6.02365892,
        5.84912726,  6.58788384,  5.72245227,  6.51354025,  5.68987254,
        6.83523894,  6.88002629,  5.86464737,  6.69985233,  6.42712472,
        5.97948586,  5.40940077,  6.31156297,  6.70203347,  6.10923648,
        5.94567711,  6.07116563,  6.42268337,  5.87284826,  6.8955506 ,
        6.04955246,  7.03701716,  6.7690469 ,  6.44846456,  5.99409098,
        5.80772334,  5.77383824,  6.03193041,  6.74495677,  5.90484667,
        6.18197985,  6.50649506,  7.17897095,  5.94794234,  6.4853657 ,
        6.44635244,  8.19680847,  6.19357436,  5.88707597,  5.64585352,
        5.73957016,  6.22880603,  6.10619147,  6.09469429,  6.16984236,
        5.81690114,  7.09740376,  6.42341305,  6.59595603,  5.69960076,
        7.11748518,  6.4197954 ,  5.94468312,  7.05993391,  5.64469199,
        7.93414685,  6.74227466,  6.66238308,  6.33628148,  8.22561696,
        6.55469714,  6.11493135,  6.45024932,  6.8683111 ,  6.25164502,
        5.96494442,  5.91709433,  6.15006431,  6.44365713,  6.69988272,
        7.03681332,  6.19511232,  5.95061831,  6.58506859,  7.15126841,
        5.64406475,  6.80011852,  6.01136667,  6.7403674 ,  5.91120206,
        6.05884373,  7.45721939,  6.93198441,  7.0756329 ,  5.69769759,
        5.99499986,  9.55237278,  7.9656805 ,  5.80282446,  6.30162648,
        6.43039813,  6.43370286,  7.39078449,  6.45644908,  6.333051  ,
        6.52462051,  6.01074205,  6.24477531,  6.27505464,  7.13651959,
        5.96909354,  6.65019128,  6.51673145,  6.67802657,  6.58498844,
        5.92427786,  6.90438109,  6.49576497,  6.11994619,  6.48438139,
        6.70550927,  6.43469491,  6.9102127 ,  6.44028909,  5.65193172,
        6.18621801,  6.34749497,  7.69975682,  6.22261447,  5.57816294,
        6.52217687,  7.94948028,  5.90849229,  5.78995822,  6.74749624,
        6.54538231,  6.11233055,  6.15366431,  5.79742699,  6.4363126 ,
        5.80522   ,  5.83391965,  6.43933752,  5.90171803,  6.97508594,
        6.47511162,  6.68378361,  6.54166793,  5.85523074,  6.94170412,
        6.33052491,  6.35867934,  6.31764243,  5.84858533,  6.14953201,
        6.45431843,  6.04380702,  7.25187546,  6.30412615,  5.90575258,
        6.45172087,  6.70991796,  6.00366095,  5.93902873,  7.10822888,
        7.04484267,  6.1062322 ,  6.42566104,  6.20377184,  5.97716923,
        9.09688977,  6.44708562,  6.36378089,  6.30788124,  6.34851919,
        5.91320037,  6.05094146,  6.08843189,  6.33761116,  6.68647361,
        7.28558696,  5.88369267,  5.81831716,  6.47864656,  5.96179678,
        6.04710435,  6.00632327,  6.15608871,  5.94370644,  5.95142098,
        6.26129077,  6.16084717,  6.54911051,  6.65401811,  6.30455519,
        6.33869199,  5.9761729 ,  6.8219931 ,  6.49647624,  6.22451929,
        5.85095411,  6.41152492,  6.82971444,  6.09316424,  6.3513206 ,
        7.3537442 ,  8.02587966,  6.58400564,  5.83724702,  5.71308104,
        6.41542072,  7.88027143,  6.76854681,  6.41583918,  7.72456905,
        6.02692742,  6.42987289,  6.88589573,  6.03705629,  6.01266741,
        5.81847581,  5.88521781,  6.47843902,  6.40094048,  6.9386258 ,
        6.50918185,  7.37670489,  6.04022072,  6.7027812 ,  7.97129474,
        5.667032  ,  6.30134597,  6.27425087,  6.44121654,  5.78910508,
        6.37522398,  6.13802408,  6.01403536,  6.07923569, 10.42232896,
        5.81701064,  6.6929865 ,  5.66144859,  7.64836821,  6.06970885,
        7.66482855,  7.15021818,  5.73907937,  6.91044773,  7.00816465,
        7.42268247,  5.93625303,  6.38337433,  6.46869506,  6.58372315,
        6.20568159,  6.26154761,  6.65780666,  6.57827224,  6.38444268,
        5.69379041,  5.60641813,  6.81442859,  5.93377003,  7.58862828,
        6.39220674,  6.02521452,  5.83845626,  5.95926353, 10.66469837,
        6.02908676,  5.70371781,  5.95369812,  7.67037693,  6.59646858,
        9.86699488,  5.91806275,  6.07221182,  6.08406952,  6.1050526 ,
        5.74238741,  5.93811455,  5.9171457 ,  7.32447183,  6.15333266,
        7.10672317,  5.93598167,  5.99253314,  5.86523774,  6.64058503,
        6.3136585 ,  6.08549748,  6.13823511,  5.70000006,  5.73122672,
        5.8690804 ,  6.89286465,  5.89062604,  6.04140067,  6.167561  ,
        6.59797452,  6.18420537,  6.22729618,  6.36669937,  6.15675684,
        6.87611213,  6.05312108,  6.72227043,  6.37326009,  6.02299821,
        6.11843381,  5.99468849,  6.27757411,  6.15790642,  6.75300204,
        6.85807015,  6.11895302,  8.25581907,  5.6595498 ,  6.14232042,
        6.5770143 ,  6.33368037,  6.76689137,  7.00661649,  5.98409742,
        6.11064449,  5.86027521,  6.04245422,  5.87572863,  6.10881253,
        6.28651308,  7.58377321,  6.08103034,  6.82925452,  6.86310695,
        6.83888807,  6.12001288,  6.65993953,  7.6752316 ,  6.43508087,
        7.47535674,  7.03011855,  6.57779147,  6.37566343,  6.73568608,
        6.59515775,  7.66768608,  6.24842859,  6.46554374,  7.23298334,
        6.14017329,  6.31792255,  6.01220764,  6.76173518,  5.64701079,
        6.56848577,  5.97890944,  6.06093829,  6.10379742,  5.80686702,
        6.28243399,  7.04786523,  5.73648904,  6.05909793,  7.04155029,
        6.14810088,  6.092187  ,  6.41011302,  6.12397594])

In [79]:
y_pred_linear.min(), y_pred_linear.max()

(4.2290096940356765, 10.664698367074877)

In [80]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred_linear, y_test)

0.7064048678599876

In [81]:
from sklearn.svm import SVR
svr_rbf = SVR(kernel='rbf', gamma=0.1)
svr_lin = SVR(kernel='linear', gamma='auto')
svr_poly = SVR(kernel='poly', gamma='auto', degree=3)
svr_rbf.fit(X_train_rfe, y_train)
y_pred_svm_rbf = svr_rbf.predict(X_test_rfe)
y_pred_svm_rbf

array([7.13693576, 6.08113513, 6.77808165, 6.59318336, 6.26117227,
       6.76335536, 6.94767209, 6.3861124 , 6.1395267 , 7.06277244,
       5.96135133, 6.21115658, 6.42724741, 6.75124309, 6.21902249,
       7.76001253, 7.11317133, 6.26515929, 6.80258488, 6.05281246,
       6.10723795, 6.25076868, 6.65536616, 6.5606972 , 6.09113033,
       6.69135271, 6.80187125, 6.86217694, 7.49892584, 6.89491778,
       6.74152486, 7.05190519, 6.45804696, 8.30881778, 6.11161271,
       6.24325829, 6.21618488, 8.05413198, 6.47557152, 6.56259474,
       6.45950159, 7.33496651, 6.00391353, 7.13339919, 6.85608267,
       5.9068141 , 6.24892883, 6.08417666, 6.13227679, 5.73604416,
       6.56252083, 6.33413872, 5.83216684, 6.63872997, 7.30683801,
       6.52196493, 6.11905187, 7.54156147, 8.441141  , 6.80261269,
       7.07092282, 6.78956984, 9.09365559, 7.00108708, 8.21972302,
       6.40869278, 7.23921413, 5.81769794, 6.59008364, 7.14253524,
       6.30329565, 7.20499307, 6.16348681, 6.27976562, 6.57121336,
       6.28424963, 6.32279469, 6.44937533, 6.47258632, 6.22265266,
       6.82906996, 6.29666384, 5.82510803, 6.28262025, 7.01506714,
       7.19284676, 8.93486362, 6.30633494, 6.14639514, 6.25963859,
       6.54307126, 6.84924592, 6.41804702, 6.76130583, 6.82113819,
       7.44165915, 6.35810801, 7.26880745, 6.4869866 , 6.88681264,
       5.87366716, 6.65960136, 6.47891934, 6.31504331, 6.3066754 ,
       6.13506366, 7.09993901, 6.53675109, 7.58248009, 6.42160614,
       6.78990162, 6.93072243, 6.60932993, 5.9103457 , 6.83062692,
       6.57711549, 5.91283778, 7.07138714, 7.74251159, 6.22161514,
       7.65437436, 6.29988163, 5.9602958 , 6.66683713, 6.29969895,
       6.73830337, 7.92851465, 6.27801031, 6.19448194, 6.31086516,
       6.58691878, 6.09726171, 6.24987731, 7.07046708, 6.56944831,
       6.34721377, 5.94517616, 6.74094491, 7.1094273 , 8.04569318,
       6.33946892, 6.66152754, 7.41686082, 6.25864936, 6.1539585 ,
       6.53168879, 6.44693389, 6.67279085, 6.63734875, 6.31334322,
       6.72250858, 6.3118216 , 6.6830422 , 6.17721837, 6.11194276,
       6.85783505, 6.96638058, 6.44235163, 6.44888472, 6.51959539,
       5.81506029, 7.20161976, 7.19025965, 6.74409098, 6.71256295,
       6.44660866, 6.07972891, 6.35158696, 7.70104196, 6.24606284,
       6.13656875, 7.70207737, 6.444551  , 7.18939901, 6.47803328,
       7.02984768, 7.00153754, 6.57672629, 7.32990101, 6.99490573,
       6.50546905, 5.69068346, 6.15169517, 6.21041299, 6.4303461 ,
       6.2774236 , 6.22627123, 8.00424464, 7.23921248, 6.65713132,
       6.87498733, 6.92989509, 6.04660391, 6.65899749, 6.89243528,
       7.33369668, 6.38372231, 6.69954053, 6.53939361, 6.32786392,
       7.18316446, 6.78162997, 6.69172698, 6.22541458, 7.45626133,
       6.70770829, 6.3687587 , 6.33568729, 6.15583662, 6.77014524,
       6.0888132 , 6.72390634, 6.40429153, 6.26936909, 5.73557915,
       6.37992829, 6.24755853, 6.52973811, 7.3732887 , 6.48288807,
       6.69545961, 6.20842591, 6.39586229, 6.04644887, 6.40701926,
       6.48969868, 6.46231906, 6.99697267, 6.38299915, 7.54983764,
       6.59781057, 6.7736318 , 6.26184647, 6.29699378, 6.59135012,
       6.93877846, 6.7421288 , 6.32072529, 7.21433679, 7.04269318,
       8.73841154, 6.63661344, 6.33011692, 6.54979263, 6.42308222,
       6.80056075, 5.94741234, 6.5595302 , 6.13728185, 6.53792683,
       5.83896457, 6.18865037, 6.86025015, 5.78940457, 6.11119475,
       6.77348793, 6.76914296, 7.19029276, 5.99286435, 6.5243984 ,
       6.22915514, 6.38321786, 6.28607624, 6.0511558 , 5.87160794,
       6.60270667, 6.3090483 , 6.47257676, 6.11402379, 6.88730917,
       5.84811727, 6.61989531, 6.22438976, 6.35244885, 6.14968261,
       6.72080457, 5.9581535 , 6.17516959, 6.34108343, 7.01604885,
       7.32161491, 6.05830679, 7.08692253, 6.12926892, 7.76367733,
       6.02143756, 6.2338998 , 6.32635082, 6.53076377, 6.10534672,
       6.45304647, 6.34699421, 6.55661815, 6.21071558, 6.82628031,
       6.10510795, 6.63296653, 6.51674328, 6.56094942, 6.19887382,
       6.46568365, 6.65825527, 6.38654207, 5.85250478, 6.49003326,
       6.80622085, 7.09630891, 6.266852  , 6.2383163 , 6.3579086 ,
       6.49856367, 5.88552745, 5.63807313, 7.88425141, 6.10119671,
       6.62073271, 6.2910287 , 7.35293235, 7.59559265, 6.0493053 ,
       6.20170285, 6.14134301, 6.76506013, 6.03607549, 7.99478666,
       6.21401653, 6.04010422, 7.44632838, 7.39883684, 8.81818344,
       6.89122679, 7.12683039, 6.40787067, 6.17432834, 6.89967992,
       6.07914334, 7.16927148, 6.30476645, 6.38270212, 6.21852176,
       5.97282009, 7.03873329, 6.51375359, 5.947716  , 7.3377513 ,
       6.37404935, 6.86418214, 6.28827307, 5.99796137, 6.53113215,
       8.15509899, 6.21381889, 6.3661853 , 6.27167109, 6.71078349,
       7.48977334, 7.07765887, 6.48419818, 6.15975559, 6.78786846,
       6.70295906, 6.60474074, 6.31728326, 6.51585202, 7.16310953,
       6.21003583, 6.84794891, 6.13843786, 7.09849623, 6.54991828,
       6.27344733, 6.02373657, 6.99097801, 6.37162706, 7.2358919 ,
       7.19972422, 6.00771726, 6.01097171, 6.55324834, 6.19031081,
       6.6148951 , 6.50307659, 6.30045979, 6.2815652 , 6.46764972,
       6.95777078, 6.40710975, 6.46260358, 6.35229705, 6.35383017,
       6.12113152, 6.33707838, 8.07437347, 6.16951436, 5.90570986,
       6.17130166, 6.1594313 , 6.13227689, 6.62629479, 8.37531294,
       5.84692747, 6.76949013, 6.84976534, 6.09128399, 6.65683298,
       6.27841043, 6.66227026, 5.91714669, 6.73802314, 5.93505142,
       6.67687246, 7.04737197, 6.07754193, 6.76242788, 6.62122185,
       6.15724067, 7.03645098, 6.43171164, 6.84909543, 6.26769522,
       6.44821782, 6.22762498, 6.44228698, 6.02498329, 7.00608826,
       6.21073457, 7.05826469, 7.22163182, 6.48714367, 6.04875897,
       6.00067253, 5.95633735, 6.4357929 , 6.88108545, 6.06827971,
       6.38211379, 6.52940006, 7.08690904, 6.2761522 , 6.474862  ,
       6.53917492, 7.76307669, 6.29447052, 6.03162788, 6.0509349 ,
       5.90204052, 6.30407008, 6.28093524, 6.30035587, 6.4351059 ,
       5.93437683, 7.14483655, 6.48416786, 6.74803578, 5.87358811,
       7.1962986 , 6.55482701, 6.10725566, 7.42303541, 5.843972  ,
       7.81690407, 6.92105002, 6.67360878, 6.35043914, 7.97382938,
       6.52348714, 6.25608072, 6.48499023, 6.86678643, 6.42179223,
       6.12632971, 6.11701341, 6.30514228, 6.61252537, 6.76244616,
       7.01136751, 6.46618483, 6.10841812, 6.8473938 , 7.12305082,
       6.0697041 , 6.84381419, 6.20850712, 6.89313987, 6.32605975,
       6.25206323, 7.40398657, 7.1469514 , 7.04618335, 5.92007904,
       6.1525773 , 8.85657427, 5.81456025, 5.99682833, 6.45207444,
       6.58517873, 6.87731171, 7.19488783, 6.64189906, 6.4943558 ,
       6.75732033, 6.30621775, 6.42760309, 6.3304681 , 7.18366702,
       6.21163   , 6.84294995, 6.64644973, 6.73245875, 6.72867153,
       6.1367442 , 6.9234181 , 6.65772911, 6.30364297, 6.62151946,
       6.73349419, 6.6723672 , 7.16720283, 6.50890441, 6.80388987,
       6.44070064, 6.4731591 , 7.49474901, 6.40782583, 5.74979037,
       6.43755776, 7.96575173, 5.94623016, 5.9977321 , 6.75210728,
       6.58692342, 6.31398371, 6.54628352, 6.03772887, 6.57068514,
       6.0858244 , 5.96401394, 6.4897282 , 6.06959289, 6.88464637,
       6.60239462, 6.90760622, 6.70452864, 6.06329516, 7.0696709 ,
       6.52252616, 6.47167238, 6.3157022 , 6.01479864, 6.21985965,
       6.58835935, 6.21003583, 7.09068946, 6.66953881, 6.18255458,
       6.65040555, 6.73779174, 6.28249674, 6.16711735, 7.04742572,
       6.98649641, 6.18131287, 6.60386769, 6.43009634, 6.07623163,
       8.71655661, 6.47723357, 6.36017083, 6.63697496, 6.49100744,
       6.14231433, 6.27292661, 6.19911893, 6.39848332, 6.83138101,
       7.34733876, 6.06775096, 6.06808723, 6.65394358, 6.02758887,
       6.24410299, 5.83027597, 6.24479973, 6.04086759, 6.15744914,
       6.44860299, 6.42427071, 6.63993933, 6.74174758, 6.47365444,
       6.72944898, 6.10831023, 6.90590538, 6.68038255, 6.37325209,
       6.11603326, 6.43114998, 6.70939139, 6.26647393, 6.52917317,
       7.19013702, 7.78258158, 6.80526108, 6.08053568, 5.90082441,
       6.54934634, 7.84262072, 6.76494865, 6.6122349 , 7.46980144,
       6.26745859, 6.59557219, 6.94761166, 6.27203024, 6.25092203,
       6.04276981, 6.08606122, 6.85368205, 6.45053267, 6.84697145,
       6.60637083, 7.67063478, 6.38992584, 6.87872251, 7.63675191,
       5.81750928, 6.39729871, 6.46771057, 6.54159298, 6.04245775,
       6.56955316, 6.28943596, 6.20938885, 6.31875453, 9.32302064,
       5.93314922, 6.64586911, 5.80806114, 7.7303426 , 6.33264913,
       7.49308037, 7.11615044, 6.12696364, 6.8629544 , 7.09631916,
       7.14568356, 6.13600067, 6.53437839, 6.47621294, 6.67843074,
       6.23000343, 6.54123021, 6.72942941, 6.92062076, 6.55187211,
       5.91675872, 5.89189732, 6.81687795, 6.23151121, 7.5878262 ,
       6.3949337 , 6.2238142 , 5.93283066, 6.11283641, 9.26818655,
       6.62374443, 5.90713495, 6.1917037 , 7.427921  , 6.71271747,
       9.17897032, 6.18536493, 6.27385361, 6.29067996, 6.23494782,
       5.95103834, 6.14935691, 6.04755667, 7.28729415, 6.25358658,
       6.94771934, 6.05268822, 6.20954177, 6.81535812, 6.728886  ,
       6.36101573, 6.18759008, 6.26659108, 5.94387984, 5.93218617,
       6.08133629, 6.82690013, 6.10996787, 6.20792686, 6.44905255,
       6.77089605, 6.25284327, 6.24066759, 6.46249672, 6.62555344,
       6.90314991, 6.25616038, 6.93915404, 6.4678139 , 6.16304355,
       6.3627619 , 6.15288284, 6.43607866, 6.29959222, 6.80938656,
       6.96697128, 6.26132142, 7.95726525, 5.88927525, 6.32346027,
       6.57032008, 6.41479589, 6.92518897, 7.05170393, 6.06853077,
       6.43094609, 6.08897994, 6.25398295, 6.09995325, 6.21325705,
       6.31322795, 7.60703485, 6.25065889, 6.88215178, 6.81472112,
       6.81899309, 6.23692551, 6.82937088, 7.46534849, 6.47235419,
       7.37510395, 7.07006474, 6.61800403, 6.54731129, 6.8325027 ,
       6.74527076, 7.91539102, 6.38686923, 6.68558209, 7.16035352,
       6.19066998, 6.36812579, 6.10625937, 6.88634092, 5.86236157,
       6.74492303, 6.18345316, 6.19151216, 6.23660546, 5.892935  ,
       6.4744178 , 7.2002577 , 5.91410092, 6.21793135, 7.15854444,
       6.27395635, 6.30172902, 6.49407944, 6.32600592])

In [82]:
y_pred_svm_rbf.min(), y_pred_svm_rbf.max()

(5.638073133700937, 9.323020641193724)

In [83]:
mean_squared_error(y_pred_svm_rbf, y_test)

0.6805348154672604

In [84]:
mean_squared_error(y_pred_svm_rbf, y_test)

0.6805348154672604

In [85]:
svr_lin.fit(X_train_rfe, y_train)
y_pred_svm_lin = svr_lin.predict(X_test_rfe)